title: "yawr!!"
description: "sudo apt-get install opsec"
url: "https://yawr.zhmixx.ru"

author:
  name: "zhmixx"
  email: "me@zhmixx.ru"

social:
  github: zhmixx

permalink: /:year/:month/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true

theme: minima

minima:
  skin: auto

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

paginate: 5
paginate_path: "/page:num/"

sass:
  style: compressed

timezone: UTC

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "zhmixx"
      comments: true
      share: true

collections:
  unretus:
    output: true
    permalink: /unretus/:path/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

header_pages:
  tag.md
  category.md